### ISSUE TITLE
about tests example

### ISSUE THREAD

**Issue by kuangtu** [zpl-c/enet#52]
In the securities technology system, generally the market data can be sent in multicast protocol to ensure the speed and fairness of transmission. Whether related use cases can be added to the test example?

**Comment by inlife** [comment]
Enet does not implement the Multicast Protocol directly, but since it offers direct UDP capabilities, such functionality could be built on top. 

In the current server-client model, the assumption would be that the client would have to be connected to multiple instances of different servers, and each data transfer call would internally send data to multiple destinations.

Please let me know if that makes sense.

**Comment by kuangtu** [comment]
The scenario for market data distribution is outlined in the following diagram. 
![marketdata](https://github.com/zpl-c/enet/assets/3457291/049cc0d1-9213-4b8d-aa5e-fc3dd426fcf7)
In the Enet server-client model, the client establishes a connection simulating TCP, and the server subsequently polls data in a sequential manner and distributes packets to the clients?
