### ISSUE TITLE
Why use your ENet modification 

### ISSUE THREAD

**Issue by ClosetMonkey** [zpl-c/enet#9]
This is an honest question ; why break away from mainstream ENet and use your library? Very few care about ENet, but all who do will ask the same questions. 

1) Will there be a performance cost

2) Will you commit to developing your extension to the same degree as the original? Why should we use your version without knowing it's not simply a pet project 

3) will you actually be responsive to reasonable requests? Mainstream ENet strives for maturity yet ignores IPv6 as if it may be a passing craze.

**Comment by inlife** [comment]
hello
>Why use your ENet modification

Simple answer, you do not need to use it, if you don't feel like it :)
The part about "why break away", is roughly explained in disclaimer part of the readme.

An answers to every of the questions:
1. This is not a new library, it's pretty much exactly the same. You can actually check out https://github.com/zpl-c/enet/blob/master/misc/ChangeLog to see what changes have been made.
2. Could you please specify or somehow formalize the degree which the original is being developed with? Since library is more than 10 years old, and it's proven to work quite reliably on big variety of things, I think there not that many things one would need to change, at least if we are talking about major changes.
3. Sure, we are gladly gonna review any pull requests coming our way
